package verimagens;

import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author damiao regis
 */
public class VerImagens extends javax.swing.JFrame {

    /**
     * Creates new form VerImagens
     */
    int t = 0;

    Imagem i = new Imagem();
    Imagem j = new Imagem();
    Imagem k = new Imagem();
    ManipImagem pdi = new ManipImagem(i);

    public VerImagens() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu5 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        imagemOriginal = new javax.swing.JLabel();
        imagemResultante = new javax.swing.JLabel();
        imagemSobrepor = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArq = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        vermelho = new javax.swing.JMenuItem();
        verde = new javax.swing.JMenuItem();
        azul = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        bMais = new javax.swing.JMenuItem();
        bx = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();

        jMenu5.setText("jMenu5");

        jMenuItem9.setText("jMenuItem9");

        jMenu9.setText("jMenu9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imagemOriginal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        imagemResultante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        imagemSobrepor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51)));

        menuArq.setText("Arquivo ");

        jMenuItem1.setText("Abrir ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuArq.add(jMenuItem1);

        jMenuItem3.setText("Salvar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuArq.add(jMenuItem3);

        jMenuBar1.add(menuArq);

        menuEdit.setText("Editar");

        jMenuItem5.setText("Dupla Exposiçâo");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuEdit.add(jMenuItem5);

        jMenu3.setText("Converter");

        jMenuItem6.setText("RGB / YIQ");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem10.setText("YIQ/RGB");
        jMenu3.add(jMenuItem10);

        menuEdit.add(jMenu3);

        jMenuBar1.add(menuEdit);

        jMenu4.setText("Ferramentas");

        jMenu6.setText("RGB");

        vermelho.setText("Red");
        vermelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vermelhoActionPerformed(evt);
            }
        });
        jMenu6.add(vermelho);

        verde.setText("Green");
        verde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verdeActionPerformed(evt);
            }
        });
        jMenu6.add(verde);

        azul.setText("Blue");
        azul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azulActionPerformed(evt);
            }
        });
        jMenu6.add(azul);

        jMenu4.add(jMenu6);

        jMenu7.setText("Negativo");

        jMenuItem4.setText("RGB");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem4);

        jMenuItem7.setText("Banda Y");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem7);

        jMenu4.add(jMenu7);

        jMenu8.setText("Escala de cinza");

        jMenuItem12.setText("Banda R ");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem12);

        jMenuItem13.setText("Banda G");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem13);

        jMenuItem14.setText("Banda B");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem14);

        jMenuItem15.setText("Média RGB");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem15);

        jMenu4.add(jMenu8);

        jMenu10.setText("Brilho");

        bMais.setText("Aditivo");
        bMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMaisActionPerformed(evt);
            }
        });
        jMenu10.add(bMais);

        bx.setText("Multiplicativo");
        bx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bxActionPerformed(evt);
            }
        });
        jMenu10.add(bx);

        jMenu4.add(jMenu10);

        jMenu11.setText("reduçao de ruidos");

        jMenuItem11.setText("Média");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem11);

        jMenuItem2.setText("Mediana");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem2);

        jMenuItem8.setText("Moda");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem8);

        jMenuItem16.setText("Gausiano");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem16);

        jMenuItem17.setText("Filtro bordas");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem17);

        jMenuItem18.setText("filtro bordas2");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem18);

        jMenuItem19.setText("filtro bodas3");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem19);

        jMenu4.add(jMenu11);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(imagemOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imagemSobrepor, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(imagemResultante, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(imagemOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagemResultante, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagemSobrepor, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        String nameImage = JOptionPane.showInputDialog("Nome do arquivo");
        k.salvaArq(nameImage);
        if (k == null) {
            JOptionPane.showInputDialog("Não posso salvar! Arquivo nulo!");
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JFileChooser arquivoSeletor = new JFileChooser();
        if (arquivoSeletor.showOpenDialog(menuArq) == JFileChooser.APPROVE_OPTION) {
            i.setF(arquivoSeletor);
            imagemOriginal.setIcon(new ImageIcon(i.getImg()));
            imagemOriginal.setHorizontalAlignment(JLabel.CENTER);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        JFileChooser arquivoSeletor = new JFileChooser();
        if (arquivoSeletor.showOpenDialog(menuArq) == JFileChooser.APPROVE_OPTION) {
            j.setF(arquivoSeletor);
            imagemSobrepor.setIcon(new ImageIcon(j.getImg()));
            imagemSobrepor.setHorizontalAlignment(JLabel.CENTER);
        }
        k.setImg(pdi.sobreporImagem(i.getImg(), j.getImg()));
        imagemResultante.setIcon(new ImageIcon(k.getImg()));
        imagemResultante.setHorizontalAlignment(JLabel.CENTER);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        k.setImg(pdi.pretoBranco4(i.getImg()));
        imagemResultante.setIcon(new ImageIcon(k.getImg()));
        imagemResultante.setHorizontalAlignment(JLabel.CENTER);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        k.setImg(pdi.pretoBranco3(i.getImg()));
        imagemResultante.setIcon(new ImageIcon(k.getImg()));
        imagemResultante.setHorizontalAlignment(JLabel.CENTER);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        k.setImg(pdi.pretoBranco2(i.getImg()));
        imagemResultante.setIcon(new ImageIcon(k.getImg()));
        imagemResultante.setHorizontalAlignment(JLabel.CENTER);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        k.setImg(pdi.pretoBranco(i.getImg()));
        imagemResultante.setIcon(new ImageIcon(k.getImg()));
        imagemResultante.setHorizontalAlignment(JLabel.CENTER);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        k.setImg(pdi.negativoY(i.getImg()));
        imagemResultante.setIcon(new ImageIcon(k.getImg()));
        imagemResultante.setHorizontalAlignment(JLabel.CENTER);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        k.setImg(pdi.negativoRGB(i.getImg()));
        imagemResultante.setIcon(new ImageIcon(k.getImg()));
        imagemResultante.setHorizontalAlignment(JLabel.CENTER);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void azulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azulActionPerformed
        // TODO add your handling code here:
        k.setImg(pdi.bandaB(i.getImg()));
        imagemResultante.setIcon(new ImageIcon(k.getImg()));
        imagemResultante.setHorizontalAlignment(JLabel.CENTER);
    }//GEN-LAST:event_azulActionPerformed

    private void verdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verdeActionPerformed
        k.setImg(pdi.bandaG(i.getImg()));
        imagemResultante.setIcon(new ImageIcon(k.getImg()));
        imagemResultante.setHorizontalAlignment(JLabel.CENTER);
    }//GEN-LAST:event_verdeActionPerformed

    private void vermelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vermelhoActionPerformed
        k.setImg(pdi.bandaR(i.getImg()));
        imagemResultante.setIcon(new ImageIcon(k.getImg()));
        imagemResultante.setHorizontalAlignment(JLabel.CENTER);
    }//GEN-LAST:event_vermelhoActionPerformed

    private void bMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMaisActionPerformed
        // TODO add your handling code here:
        String brilhoAdtivo = JOptionPane.showInputDialog("Digite o valor da quant. de brilho. ");
        float brAd = Float.parseFloat(brilhoAdtivo);
        k.setImg(pdi.controleBrilhoAditivo(i.getImg(), brAd));
        imagemResultante.setIcon(new ImageIcon(k.getImg()));
        imagemResultante.setHorizontalAlignment(JLabel.CENTER);

    }//GEN-LAST:event_bMaisActionPerformed

    private void bxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bxActionPerformed
        // TODO add your handling code here:
        String brilhoMult = JOptionPane.showInputDialog("Digite o valor da quant. de brilho. ");
        float br = Float.parseFloat(brilhoMult);
        k.setImg(pdi.controleBrilhoMultiplicativo(i.getImg(), br));
        imagemResultante.setIcon(new ImageIcon(k.getImg()));
        imagemResultante.setHorizontalAlignment(JLabel.CENTER);
    }//GEN-LAST:event_bxActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        k.setImg(pdi.ConvertYuvRgb(pdi.ConvertRGBYIQ(i.getImg())));
        imagemResultante.setIcon(new ImageIcon(k.getImg()));
        imagemResultante.setHorizontalAlignment(JLabel.CENTER);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        String t = JOptionPane.showInputDialog("Digite tamanho da janela ");
        int tam = Integer.parseInt(t);
        k.setImg(pdi.retornoDosFiltros(i.getImg(), tam, 1));                                                                    //(pdi.retornoDosFiltrosDeRuidos(pdi.suavizar(pdi.entradaDosFiltrosDeRuidos(i.getImg()), tam, 1)));
        imagemResultante.setIcon(new ImageIcon(k.getImg()));
        imagemResultante.setHorizontalAlignment(JLabel.CENTER);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        k.setImg(pdi.retornoDosFiltros(i.getImg(), 3, 4));
        imagemResultante.setIcon(new ImageIcon(k.getImg()));
        imagemResultante.setHorizontalAlignment(JLabel.CENTER);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        String t = JOptionPane.showInputDialog("Digite tamanho da janela ");
        int tam = Integer.parseInt(t);
        k.setImg(pdi.retornoDosFiltros(i.getImg(), tam, 3));
        imagemResultante.setIcon(new ImageIcon(k.getImg()));
        imagemResultante.setHorizontalAlignment(JLabel.CENTER);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        String t = JOptionPane.showInputDialog("Digite tamanho da janela ");
        int tam = Integer.parseInt(t);
        k.setImg(pdi.retornoDosFiltros(i.getImg(), tam, 2));                                                               //(pdi.retornoDosFiltrosDeRuidos(pdi.suavizar(pdi.entradaDosFiltrosDeRuidos(i.getImg()), tam, 2)));
        imagemResultante.setIcon(new ImageIcon(k.getImg()));
        imagemResultante.setHorizontalAlignment(JLabel.CENTER);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        k.setImg(pdi.retornoDosFiltros(i.getImg(), 3, 5));
        imagemResultante.setIcon(new ImageIcon(k.getImg()));
        imagemResultante.setHorizontalAlignment(JLabel.CENTER);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        k.setImg(pdi.retornoDosFiltros(i.getImg(), 3, 6));
        imagemResultante.setIcon(new ImageIcon(k.getImg()));
        imagemResultante.setHorizontalAlignment(JLabel.CENTER);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
        k.setImg(pdi.retornoDosFiltros(i.getImg(), 3, 7));
        imagemResultante.setIcon(new ImageIcon(k.getImg()));
        imagemResultante.setHorizontalAlignment(JLabel.CENTER);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerImagens.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerImagens.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerImagens.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerImagens.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerImagens().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem azul;
    private javax.swing.JMenuItem bMais;
    private javax.swing.JMenuItem bx;
    private javax.swing.JLabel imagemOriginal;
    private javax.swing.JLabel imagemResultante;
    private javax.swing.JLabel imagemSobrepor;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu menuArq;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenuItem verde;
    private javax.swing.JMenuItem vermelho;
    // End of variables declaration//GEN-END:variables
}
